# Site settings
email: miliam5234@gmail.com
baseurl: "https://danb11.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Danbbbb
description: Danb's Blog
url: "https://danb11.github.io"
twitter_username:
default_img:

# Profile settings
name: Danbee, Lee
profile_img: /assets/images/profile.jpeg
profile: ì‹œê°ë””ìì¸ì„ ì „ê³µí–ˆê³ , ì§€ê¸ˆì€ iOSë¥¼ ê³µë¶€í•˜ê³  ìˆìŠµë‹ˆë‹¤. ë””ë°œìë¥¼ ê¿ˆêµ¬ëŠ” ê°œë°œê¿ˆë‚˜ë¬´ğŸŒ³ì…ë‹ˆë‹¤. I studied Visual Design. Now I'm learning iOS development. If you have any questions please feel free to contact me
social:
  github: https://github.com/danb11
  facebook: https://www.facebook.com/ldbbb


# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "categories.sh"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

kramdown:
  parse_block_html: true

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
